### appspec.yml ###
version: 0.0
os: linux
files:
  - source: /webapp/target/webapp.war
    destination: /home/ubuntu/

# file_exists_behavior: OVERWRITE
# hooks:
#   ApplicationStop:
#     - location: scripts/application_stop.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       runas: root
