### appspec.yml ###
version: 0.0
os: linux
files:
  - source: /webapp.war
    destination: /home/ec2-user/
file_exists_behavior: OVERWRITE
# hooks:
#   ApplicationStop:
#     - location: scripts/application_stop.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       runas: root
