version: 0.0
os: linux
files:
  - source: /webapp.war
    destination: /tmp/

file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: application_stop_start.sh
      timeout: 300
      runas: root
