### appspec.yml ###
version: 0.0
os: linux
files:
  - source: /webapp.war
    destination: /home/ubuntu/

file_exists_behavior: OVERWRITE
hooks:
  # ApplicationStop:
  #   - location: application_stop.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
