version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
     commands:
        - apt-get update -y
        - apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `d
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
