version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - yum update -y
      - yum install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
      - scp -i $narsan.pem.pem target/webapp.war  ec2-user@13.126.207.243:/home/ec2-user/webapp.war            #/path/to/tomcat/webapps/
      # Replace "/path/to/your/private-key.pem", "your-app.war", "user", "your-linux-machine-ip", and "/path/to/tomcat/webapps/" with your actual values
