version: 0.2

phases:
  install:
    commands:
      - echo "Skipping yum update..."

  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."

  build:
    commands:
      - echo "Build started"
      - mvn clean package
      - ls
      - cp webapp/target/webapp.war .
      - mv webapp.war webapps.war
      - zip -r Output_Package.zip webapps.war buildspec.yml
      - ls
     

  post_build:
    commands:
      # - echo "Build completed"

artifacts:
  files: Output_Package.zip
  discard-paths: yes
