connection:
  region: us2
scan_info:
  - app_name: gowdasagar.online
    scan_config_name: http://gowdasagar.online
status_check_interval: 60
# jira:
#   url: https://kumarsanthosh653.atlassian.net
#   user: kumarsanthosh653@gmail.com
#   token: ATATT3xFfGF0k1qdgA_PSCrFEJ7bJ5WlunSmuWjQcdFrrG0mUFrvxzdoxha7HasD3dd8zF8up7nFL8tcuue9nkakKRAfkDJmoqL2nOSzcGEjBbzVU7DZ0FMQvNsRy0gcg-cJfc7wmPvlpwjpr4Adl_151NDvxzXYOiRXfaG6XSeiW2Q2yDFNt4U=CD90DFF0
#   project_key: KAN


